name: probody_ems
description: EMS cihazını kontrol etmek için mobil uygulama

# SDK kısıtlaması
environment:
  sdk: '^3.7.0'
  flutter: ">=3.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  
  # Bluetooth
  flutter_blue_plus: ^1.14.1
  permission_handler: ^10.4.3
  
  # UI
  flutter_svg: ^2.0.7
  
  # Diğer
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700